### ISSUE TITLE
Suggestion: change title color

### ISSUE THREAD

**Issue by Y581515** [Yo581515/github-crash-course#1]
i think it look better if the main title is vlue

the style could be like 

```css
h1 {
  color: #274bff;
}
```
